export const collection = {
  SYSTEM_USERS: "system_users",
  CLUBS: "clubs",
  POSTS: "posts",
  ORGANIZERS: "organizers",
  EVENTS: "events",
  CALENDAR_INDEX: "calendar_index",
  EXPERTS: "experts",
  ADMIN_POSTS: "latest_news",
  PODCASTS: "podcasts",
  FEATURED_PODCASTS: "featured_podcast",
  PODCAST_CATEGORIES: "podcast_categories",
  USER_PROGRAM: "user_programs",
  TASKS: "tasks",
  USER_TASKS: "user_tasks",
  TASK_GROUP: "task_group",
  TASK_ACTION_HISTORY: "user_tasks_history",
  PROGRAM: "programs",
  USERS_REPORTS: "user_reports",
  USERS: "users",
  FEEDBACKS: "user_feedbacks",
  ROLES: "roles",
  PERMISSIONS: "permissions",
  BADGES: "badges",
  GROUP_TASKS: "group-task",
  PROGRAMS: "programs",
  CLUB_CODES:'club_codes',
  UPLOADS:'uploads'
};
